title: Jordan # name of the site
author: Jordan Ayala # name of site's author
email: nothingrightnow@gmail.com # email of site's author
university-email: nothingrightnow@psu.edu #my school email
url: https://somethingthatiwillbuy # root address of the site
description: > # description of the site (multiple lines allowed)
  My portfolio
permalink: /:slug.html

favicon: "assets/j-icon.png" # relative path to site's favicon
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: "back" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed
